---
name: Containers Continuous-Integration
run-name: CI ${{ github.repository }} - ${{ github.ref }} job 🚀
on:
  push:
    branches: [main,app-version-updates]
  pull_request:
jobs:
  Build-Test-Container-Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v7

      - name: Identify changed application subdirectories
        id: changed-dirs
        uses: tj-actions/changed-files@v47
        with:
          dir_names: "true"
          dir_names_max_depth: "1"
          dir_names_exclude_root: "true"
          files_ignore: |
            .github/**
            docs/**
            *.md
            *.txt
            *.json

      - name: Install workflow dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yq

      - name: Build modified application Docker images
        run: |
          for dir in ${{ steps.changed-dirs.outputs.all_changed_files }}; do
            [ -f "$dir/meta.yml" ] || continue
            version=$(cat $dir/meta.yml | yq -r .version)
            docker build $dir/ --file $dir/Dockerfile --build-arg VERSION=$version --tag 0labs/$dir:$version
          done

      - name: Test application docker-compose setups
        run: |
          for dir in ${{ steps.changed-dirs.outputs.all_changed_files }}; do
            [ -f "$dir/docker-compose.yaml" ] || continue
            docker-compose -f $dir/docker-compose.yaml up -d --build
            docker-compose -f $dir/docker-compose.yaml down
          done